CREATE TABLE dwd_db.dwd_orders_10x USING PARQUET AS
SELECT * FROM dwd_db.dwd_orders
CROSS JOIN (
  SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
  UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
) t;

DROP TABLE dwd_db.dwd_orders;

ALTER TABLE dwd_db.dwd_orders_10x RENAME TO dwd_db.dwd_orders;